[package]
name = "reddit-scrape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.44"
regex = "1.9.5"
scraper = "0.17.1"
